USE DATABASE ATM_STREAMING_DB;
USE SCHEMA ATM_DATA;

CREATE OR REPLACE TABLE BANK_FRAUD (
    TRANSACTION_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    TRANSACTION_DATE VARCHAR,
    TRANSACTION_TIME VARCHAR,
    HOUR_OF_DAY NUMBER,
    IS_WEEKEND NUMBER,
    IS_NIGHT_TRANSACTION NUMBER,
    COUNTRY VARCHAR,
    CITY VARCHAR,
    MERCHANT_CATEGORY VARCHAR,
    PAYMENT_METHOD VARCHAR,
    DEVICE_TYPE VARCHAR,
    CUSTOMER_AGE NUMBER,
    CREDIT_SCORE NUMBER,
    ACCOUNT_AGE_YEARS FLOAT,
    ACCOUNT_BALANCE FLOAT,
    TRANSACTION_AMOUNT FLOAT,
    NUM_PREV_TRANSACTIONS NUMBER,
    TRANSACTION_FREQ_MONTHLY NUMBER,
    DISTANCE_FROM_HOME_KM FLOAT,
    TIME_SINCE_LAST_TXN_HRS FLOAT,
    IS_INTERNATIONAL NUMBER,
    FAILED_ATTEMPTS NUMBER,
    PIN_CHANGED_RECENTLY NUMBER,
    IS_FRAUD NUMBER,
    FRAUD_TYPE VARCHAR
);

SELECT COUNT(*)
FROM BANK_FRAUD;

SELECT *
FROM BANK_FRAUD
LIMIT 10;

SELECT 
    IS_FRAUD,
    COUNT(*) AS TRANSACTION_COUNT
FROM BANK_FRAUD
GROUP BY IS_FRAUD
ORDER BY IS_FRAUD;
#

SELECT IS_FRAUD, COUNT(*)
FROM BANK_FRAUD
GROUP BY IS_FRAUD
ORDER BY IS_FRAUD;